import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <nav className="flex flex-row bg-blue-950 p-4">
          <div className="text-white text-xl font-bold p-4 hover:text-gray-500">
            <Link href="/contacts">Contact List</Link>
          </div>
          <div className="text-white text-xl font-bold p-4 hover:text-gray-500">
            <Link href="/contacts/new">Add New Contact</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
